package com.example.nimmaguru

import androidx.compose.runtime.mutableStateListOf

object DataStore {
    val tutorList = mutableStateListOf<TutorModel>(
        TutorModel(
            name = "Ramesh Rao",
            category = Category.SCHOOL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Mathematics",
            education = "M.Sc Mathematics",
            jobTitle = "Retired HOD Math",
            experience = "35",
            village = "Kengeri",
            phone = "9845012345",
            rating = 4.9f,
            ratingCount = 120,
            freeHours = "Sat 4:00 PM - 6:00 PM",
            thankYouNotes = listOf("Excellent teaching style!", "Very patient with kids")
        ),
        TutorModel(
            name = "Sagar M",
            category = Category.ENGINEERING,
            tutorType = TutorType.STUDENT,
            subject = "Data Structures",
            education = "BE 3rd Year (CSE)",
            college = "RVCE",
            experience = "2",
            village = "Malleswaram",
            phone = "9900112233",
            rating = 4.8f,
            ratingCount = 45,
            freeHours = "Sun 10:00 AM - 12:00 PM"
        ),
        TutorModel(
            name = "Dr. Sandeep Hegde",
            category = Category.MEDICAL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Anatomy",
            education = "MBBS, MD",
            jobTitle = "Associate Professor",
            experience = "15",
            village = "Jayanagar",
            phone = "9880011223",
            rating = 5.0f,
            ratingCount = 89,
            freeHours = "Mon 6:00 PM - 8:00 PM"
        ),
        TutorModel(
            name = "Latha Mani",
            category = Category.SCHOOL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Kannada",
            education = "B.A. Kannada",
            jobTitle = "Primary School Teacher",
            experience = "20",
            village = "Jayanagar",
            phone = "9448001122",
            rating = 4.9f,
            ratingCount = 67,
            freeHours = "Sun 2:00 PM - 4:00 PM",
            thankYouNotes = listOf("Kannada grammar is now easy for me.")
        ),
        TutorModel(
            name = "Dr. Anupama Sharma",
            category = Category.MEDICAL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Physiology",
            education = "MBBS, MS",
            jobTitle = "Professor",
            experience = "18",
            village = "Indiranagar",
            phone = "9876543211",
            rating = 4.9f,
            ratingCount = 50,
            freeHours = "Fri 5:00 PM - 7:00 PM"
        ),
        TutorModel(
            name = "Karthik Raj",
            category = Category.ENGINEERING,
            tutorType = TutorType.STUDENT,
            subject = "Python Programming",
            education = "BE 4th Year",
            college = "PESIT",
            experience = "1",
            village = "Banashankari",
            phone = "9876543212",
            rating = 4.7f,
            ratingCount = 30,
            freeHours = "Sat 10:00 AM - 12:00 PM"
        ),
        TutorModel(
            name = "Suma Rao",
            category = Category.SCHOOL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "English",
            education = "MA English",
            jobTitle = "High School Teacher",
            experience = "12",
            village = "Vijayanagar",
            phone = "9876543213",
            rating = 4.8f,
            ratingCount = 40,
            freeHours = "Tue 4:00 PM - 6:00 PM"
        ),
        TutorModel(
            name = "Vijay Kumar",
            category = Category.COMMERCE,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Accountancy",
            education = "M.Com",
            jobTitle = "Chartered Accountant",
            experience = "8",
            village = "Whitefield",
            phone = "9876543214",
            rating = 4.6f,
            ratingCount = 25,
            freeHours = "Sun 11:00 AM - 1:00 PM"
        ),
        TutorModel(
            name = "Meera Bai",
            category = Category.SKILLS,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Carnatic Music",
            education = "MA Music",
            jobTitle = "Music Teacher",
            experience = "25",
            village = "Basavanagudi",
            phone = "9876543215",
            rating = 5.0f,
            ratingCount = 100,
            freeHours = "Wed 5:00 PM - 7:00 PM"
        ),
        TutorModel(
            name = "Ravi Teja",
            category = Category.SCHOOL,
            tutorType = TutorType.STUDENT,
            subject = "Science",
            education = "B.Sc 2nd Year",
            college = "National College",
            experience = "1",
            village = "Koramangala",
            phone = "9876543216",
            rating = 4.5f,
            ratingCount = 15,
            freeHours = "Thu 6:00 PM - 8:00 PM"
        ),
        TutorModel(
            name = "Shanti K",
            category = Category.OTHER,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Yoga",
            education = "Certified Yoga Instructor",
            jobTitle = "Yoga Coach",
            experience = "10",
            village = "Hebbal",
            phone = "9876543217",
            rating = 4.9f,
            ratingCount = 60,
            freeHours = "Daily 6:00 AM - 7:00 AM"
        ),
        TutorModel(
            name = "Anil Gupta",
            category = Category.ENGINEERING,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Java",
            education = "M.Tech",
            jobTitle = "Senior Software Engineer",
            experience = "10",
            village = "HSR Layout",
            phone = "9876543218",
            rating = 4.7f,
            ratingCount = 55,
            freeHours = "Sat 2:00 PM - 4:00 PM"
        ),
        TutorModel(
            name = "Priya S",
            category = Category.SCHOOL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Social Studies",
            education = "B.Ed",
            jobTitle = "Middle School Teacher",
            experience = "7",
            village = "Yelahanka",
            phone = "9876543219",
            rating = 4.6f,
            ratingCount = 22,
            freeHours = "Mon 4:00 PM - 5:00 PM"
        ),
        TutorModel(
            name = "Suresh M",
            category = Category.COMMERCE,
            tutorType = TutorType.STUDENT,
            subject = "Economics",
            education = "B.Com Final Year",
            college = "St. Joseph's",
            experience = "1",
            village = "Ulsoor",
            phone = "9876543220",
            rating = 4.4f,
            ratingCount = 10,
            freeHours = "Sat 5:00 PM - 7:00 PM"
        ),
        TutorModel(
            name = "Mohan Das",
            category = Category.SCHOOL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Hindi",
            education = "M.A. Hindi",
            experience = "15",
            village = "Tumakuru",
            phone = "9876543221",
            rating = 4.8f,
            freeHours = "Sun 4:00 PM - 6:00 PM"
        ),
        TutorModel(
            name = "Rekha Shetty",
            category = Category.SKILLS,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Tailoring",
            education = "Diploma in Fashion",
            experience = "12",
            village = "Mangaluru",
            phone = "9876543222",
            rating = 4.9f,
            freeHours = "Mon-Fri 3:00 PM - 5:00 PM"
        ),
        TutorModel(
            name = "Dr. Vikram K",
            category = Category.MEDICAL,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Biochemistry",
            education = "MBBS, Ph.D",
            experience = "22",
            village = "Mysuru",
            phone = "9876543223",
            rating = 5.0f,
            freeHours = "Sat 11:00 AM - 1:00 PM"
        ),
        TutorModel(
            name = "Sunitha R",
            category = Category.COMMERCE,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Business Studies",
            education = "MBA",
            experience = "6",
            village = "Dharwad",
            phone = "9876543224",
            rating = 4.5f,
            freeHours = "Tue 6:00 PM - 7:00 PM"
        ),
        TutorModel(
            name = "Pavan Kumar",
            category = Category.ENGINEERING,
            tutorType = TutorType.STUDENT,
            subject = "Digital Logic",
            education = "BE 2nd Year",
            college = "MSRIT",
            experience = "1",
            village = "Kengeri",
            phone = "9876543225",
            rating = 4.3f,
            freeHours = "Sun 2:00 PM - 4:00 PM"
        ),
        TutorModel(
            name = "Gouri Amma",
            category = Category.SKILLS,
            tutorType = TutorType.WORKING_PROFESSIONAL,
            subject = "Traditional Cooking",
            education = "Home Maker",
            experience = "40",
            village = "Chamarajanagar",
            phone = "9876543226",
            rating = 5.0f,
            freeHours = "Weekends"
        )
    )

    val studentList = mutableStateListOf<StudentModel>(
        StudentModel(name = "Aditi R", grade = "1st Std", subjectsNeeded = listOf("Maths", "EVS"), village = "Rajajinagar", contactNumber = "9000000001"),
        StudentModel(name = "Arjun K", grade = "10th Std", subjectsNeeded = listOf("Maths"), village = "Kengeri", contactNumber = "9000000010"),
        StudentModel(name = "Megha S", grade = "MBBS 1st Year", subjectsNeeded = listOf("Anatomy"), village = "Jayanagar", contactNumber = "9000000014"),
        StudentModel(name = "Rohan P", grade = "8th Std", subjectsNeeded = listOf("Science"), village = "Hebbal", contactNumber = "9000000002"),
        StudentModel(name = "Kavya L", grade = "12th Std", subjectsNeeded = listOf("Physics", "Chemistry"), village = "Banashankari", contactNumber = "9000000003"),
        StudentModel(name = "Vikram Singh", grade = "BE 2nd Year", subjectsNeeded = listOf("Mathematics"), village = "Indiranagar", contactNumber = "9000000004"),
        StudentModel(name = "Sneha K", grade = "5th Std", subjectsNeeded = listOf("All Subjects"), village = "Koramangala", contactNumber = "9000000005"),
        StudentModel(name = "Rahul Dravid", grade = "9th Std", subjectsNeeded = listOf("English", "Social"), village = "Basavanagudi", contactNumber = "9000000006"),
        StudentModel(name = "Divya G", grade = "B.Com 1st Year", subjectsNeeded = listOf("Accountancy"), village = "Whitefield", contactNumber = "9000000007"),
        StudentModel(name = "Akash V", grade = "7th Std", subjectsNeeded = listOf("Kannada"), village = "Malleswaram", contactNumber = "9000000008"),
        StudentModel(name = "Nidhi J", grade = "10th Std", subjectsNeeded = listOf("Maths", "Science"), village = "Vijayanagar", contactNumber = "9000000009"),
        StudentModel(name = "Varun C", grade = "BE 1st Year", subjectsNeeded = listOf("Physics"), village = "Yelahanka", contactNumber = "9000000011"),
        StudentModel(name = "Preeti H", grade = "11th Std", subjectsNeeded = listOf("Biology"), village = "Jayanagar", contactNumber = "9000000012"),
        StudentModel(name = "Abhay M", grade = "PUC 1st Year", subjectsNeeded = listOf("Physics"), village = "Mysuru", contactNumber = "9000000021"),
        StudentModel(name = "Ishani R", grade = "4th Std", subjectsNeeded = listOf("Kannada"), village = "Hubballi", contactNumber = "9000000022"),
        StudentModel(name = "Tanmay K", grade = "6th Std", subjectsNeeded = listOf("English"), village = "Belagavi", contactNumber = "9000000023"),
        StudentModel(name = "Prisha S", grade = "9th Std", subjectsNeeded = listOf("Science"), village = "Kalaburagi", contactNumber = "9000000024"),
        StudentModel(name = "Vedant V", grade = "7th Std", subjectsNeeded = listOf("Maths"), village = "Ballari", contactNumber = "9000000025"),
        StudentModel(name = "Ananya D", grade = "PUC 2nd Year", subjectsNeeded = listOf("Economics"), village = "Shivamogga", contactNumber = "9000000026"),
        StudentModel(name = "Manjunath B", grade = "5th Std", subjectsNeeded = listOf("All"), village = "Raichur", contactNumber = "9000000027")
    )

    fun updateTutor(updatedTutor: TutorModel) {
        val index = tutorList.indexOfFirst { it.id == updatedTutor.id }
        if (index != -1) {
            tutorList[index] = updatedTutor
        }
    }
}
